# Travis CI build file for Kitura-redis.
branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "khwsHN8HcW67X2D90onBZDEQM9x8w35xvXjnQ++TYOj3SlD9TlZiL3k0KheJ2z5EeBWnYND8jp5v7B2B9Sq3MsRuilV6DI5sKWrdWwJGZfi1e9wZivKsq0llssroHkyHzpAI2S4oD2EJ9uCzNNhsrXVi1QhESz0ZE8YTwR90pxGFAGAQ2uOoXiaf8vTFv5Z3BrB/vetjgGkAzt2J+GOFBI3jHYrMe3lKgjOy90gZHCJjRbp8n7WtBkscaa4RDsfSlgn/40tVC4kZUvMG24Mzl7kMf63fJfksxrJQjDDv814/3/UhwkVG61MHjshwVZ9Gna1cRvUHCQidSsMqz/f7X4vFzRqfkEya48HgeFjDLQHfxRoEAf9+npNCkaghR8lQjB9LvXQXU1fBEOmE/tpx4j0Oqc6arYJwR0qFQ/ziz/Kse0rZuUJ+rvNlTPx49j0uTuiD5av/oH/3KtAp+8Sl5ibynYc8VOrLTfdH07l/hdUdUvsSGXKVtNa2v6WJmrXyKeUziSL7/43Pol1PDO154jbwluv6Xnqbjt+nTYWsuhNRvYLSylGJcnYINxBmkhFQEjPQJ7j2hzEfriVVWsAS1vn1jJt7Pfi0UWpf/96siIreJ4zb9+Y7jvuhOlMF5yeeHMADEznHmjX2cqxYSiydRk2r1rCWjgTTsxnUVFucIeg="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.1
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Kitura-CI.git
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
